export const HOMEPAGE_REQUEST = '@HOMEPAGE/HOMEPAGE_REQUEST';
export const HOMEPAGE_REQUEST_FAIL = '@HOMEPAGE/HOMEPAGE_REQUEST_FAIL';
export const HOMEPAGE_REQUEST_SUCC = '@HOMEPAGE/HOMEPAGE_REQUEST_SUCC';

export const LEFT_STORY_MOVE_ON = '@left/LEFT_STORY_MOVE_ON';
export const LEFT_STORY_MOVE_OUT = '@left/LEFT_STORY_MOVE_OUT';
export const LEFT_STORY_REQUEST = '@left/LEFT_STORY_REQUEST';
export const LEFT_STORY_REQUEST_SUCC = '@left/LEFT_STORY_REQUEST_SUCC';
export const LEFT_STORY_REQUEST_FAIL = '@left/LEFT_STORY_REQUEST_FAIL';

export const LEFT_ACTIVITY_MOVE_ON = '@left/LEFT_ACTIVITY_MOVE_ON';
export const LEFT_ACTIVITY_MOVE_OUT = '@left/LEFT_ACTIVITY_MOVE_OUT';
export const LEFT_ACTIVITY_REQUEST = '@left/LEFT_ACTIVITY_REQUEST';
export const LEFT_ACTIVITY_REQUEST_SUCC = '@left/LEFT_ACTIVITY_REQUEST_SUCC';
export const LEFT_ACTIVITY_REQUEST_FAIL = '@left/LEFT_ACTIVITY_REQUEST_FAIL';

export const LEFT_PARTY_MOVE_ON = '@left/LEFT_PARTY_MOVE_ON';
export const LEFT_PARTY_MOVE_OUT = '@left/LEFT_PARTY_MOVE_OUT';
export const LEFT_PARTY_REQUEST = '@left/LEFT_PARTY_REQUEST';
export const LEFT_PARTY_REQUEST_SUCC = '@left/LEFT_PARTY_REQUEST_SUCC';
export const LEFT_PARTY_REQUEST_FAIL = '@left/LEFT_PARTY_REQUEST_FAIL';

export const LEFT_MINE_MOVE_ON = '@left/LEFT_MINE_MOVE_ON';
export const LEFT_MINE_MOVE_OUT = '@left/LEFT_MINE_MOVE_OUT';
export const LEFT_MINE_REQUEST = '@left/LEFT_MINE_REQUEST';
export const LEFT_MINE_REQUEST_SUCC = '@left/LEFT_MINE_REQUEST_SUCC';
export const LEFT_MINE_REQUEST_FAIL = '@left/LEFT_MINE_REQUEST_FAIL';

export const LEFT_CONNECT_MOVE_ON = '@left/LEFT_CONNECT_MOVE_ON';
export const LEFT_CONNECT_MOVE_OUT = '@left/LEFT_CONNECT_MOVE_OUT';
export const LEFT_CONNECT_REQUEST = '@left/LEFT_CONNECT_REQUEST';
export const LEFT_CONNECT_REQUEST_SUCC = '@left/LEFT_CONNECT_REQUEST_SUCC';
export const LEFT_CONNECT_REQUEST_FAIL = '@left/LEFT_CONNECT_REQUEST_FAIL';

export const HIDE_LEFT_APPEAR_BOX = '@left/HIDE_LEFT_APPEAR_BOX';

export const GET_PAGE_REQUEST = '@left/GET_PAGE_REQUEST';
export const GET_PAGE_REQUEST_SUCC = '@left/GET_PAGE_REQUEST_SUCC';
export const GET_PAGE_REQUEST_FAIL = '@left/GET_PAGE_REQUEST_FAIL';

export const SHOW_LEFT_DIA = '@left/SHOW_LEFT_DIA';
export const HIDE_LEFT_DIA = '@left/HIDE_LEFT_DIA';
